---
# This playbook will install postgresql and create db user and give permissions.

- name: Install postgresql and packages
  apt: pkg=$item state=present
  with_items:
    - python-psycopg2
    - libpq-dev
    - postgresql

- name: Start PostgreSQL and enable at boot
  service: name=postgresql enabled=yes state=started
