---
# This playbook contains common plays that will be run on all nodes.

- name: chmod the directories in /vagrant/ dir to 755
  shell: find /vagrant/ -type d -print0 | xargs -0 chmod 755

- name: chmod the files in /vagrant/ dir to 644
  shell: find /vagrant/ -type f -print0 | xargs -0 chmod 644

- name: ensure apt cache is up to date
  action: apt update_cache=yes

- name: install vim
  apt: name=vim state=present
  tags: vim

- name: install git
  apt: pkg=git state=present
